### ISSUE TITLE
Not able to minify JS files

### ISSUE THREAD

**Issue by gwduvalljr** [Josee9988/MinifyAll#48] opened 2020-05-26 12:16 UTC
I am using VS Code. I installed MinifyAll. I am right clicking on a *.js file. All I get is "We will not format this file type because it is disabled." I have checked the settings and JavaScript is not disabled. What am I missing?

**Comment by Josee9988** [comment] 2020-05-26 12:18
Could you share your vscode settings or the minifyall settings that you are using?

**Comment by gwduvalljr** [comment] 2020-05-26 12:21
Here is a screenshot of the settings page. Let me know if there is something else you need.

![Screenshot 2020-05-26 at 8 19 48 AM](https://user-images.githubusercontent.com/6506735/82899947-c53ff500-9f29-11ea-970b-31bdc18f5175.png)

**Comment by Josee9988** [comment] 2020-05-26 12:22
I'll check it ASAP. thanks for contributing!

**Comment by gwduvalljr** [comment] 2020-05-26 12:23
I really appreciate it. Thank you!

**Comment by Josee9988** [comment] 2020-05-26 12:26
You can minimize it if you open the file, right? It is just if you right-click it from the menu, am I right?

**Comment by gwduvalljr** [comment] 2020-05-26 12:28
That appears to be correct. I just tried it and minifying from the open file worked.

**Comment by Josee9988** [comment] 2020-05-26 12:31
There is I problem with the right-click in the menu, I will see what is wrong. and close this issue when the problem is resolved.

Thanks :)

**Comment by gwduvalljr** [comment] 2020-05-26 12:32
OK, thanks!

**Closed** 2020-05-26 13:15 UTC
Labels: bug

**Comment by Josee9988** [comment] 2020-05-26 13:23
Version 2.3.1 is out now, check it out and if you found any other issue just let us know.

Thanks for contributing @gwduvalljr !
